[tools]
go = "prefix:1.24"
python = "3.12"

[tasks]
init = "go mod init $(basename $PWD)"
install = "brew install golangci-lint && pre-commit install"
checks = "pre-commit run --all-files"
lint = "pre-commit run go-lint"
tests = "pre-commit run go-unit-tests"
