[tools]
go = "prefix:1.24" # 1.24.2
python = "3.12"    # 3.12.9

[tasks]
init = "go mod init $(basename $PWD)"
install = "brew install golangci-lint && pre-commit install"
checks = "pre-commit run --all-files"
lint = "pre-commit run golangci-lint --all-files"
tests = "go test"
